language: node_js

node_js:
  - "8.0.0"

addons:
  ssh_known_hosts:
  - 54.201.138.198
  - 54.202.240.163
  - 54.191.235.10
  - 34.219.213.219
  - engine.internal.staging.october.news

notifications:
  email: false

before_install:
- npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
- yarn config set //registry.npmjs.org/:_authToken $NPM_TOKEN

install:
  - ./scripts/ci/setup.sh

script:
  - ./scripts/ci/test.sh

after_success:
  - ./scripts/ci/deploy.sh
