language: node_js

node_js:
  - "8.0.0"

addons:
  ssh_known_hosts:
  - engine.internal.october.news
  - engine.internal.development.october.news

notifications:
  email: false

before_install:
- npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

install:
  - ./scripts/ci/setup.sh

script:
  - ./scripts/ci/test.sh

after_success:
  - ./scripts/ci/deploy.sh
