/* Graph Explorer */

export const CONNECT_USERS_REQUEST = "CONNECT_USERS_REQUEST"
export const CONNECT_USERS_SUCCESS = "CONNECT_USERS_SUCCESS"
export const CONNECT_USERS_ERROR = "CONNECT_USERS_ERROR"

export const GET_BLACKLIST_REQUEST = "GET_BLACKLIST_REQUEST"
export const GET_BLACKLIST_SUCCESS = "GET_BLACKLIST_SUCCESS"
export const GET_BLACKLIST_ERROR = "GET_BLACKLIST_ERROR"

export const SET_BLACKLIST_REQUEST = "SET_BLACKLIST_REQUEST"
export const SET_BLACKLIST_SUCCESS = "SET_BLACKLIST_SUCCESS"
export const SET_BLACKLIST_ERROR = "SET_BLACKLIST_ERROR"

export const REMOVE_BLACKLIST_REQUEST = "REMOVE_BLACKLIST_REQUEST"
export const REMOVE_BLACKLIST_SUCCESS = "REMOVE_BLACKLIST_SUCCESS"
export const REMOVE_BLACKLIST_ERROR = "REMOVE_BLACKLIST_ERROR"

export const GET_USERS_REQUEST = "GET_USERS_REQUEST"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_ERROR = "GET_USERS_ERROR"

export const GET_SESSIONS_REQUEST = "GET_SESSIONS_REQUEST"
export const GET_SESSIONS_SUCCESS = "GET_SESSIONS_SUCCESS"
export const GET_SESSIONS_ERROR = "GET_SESSIONS_ERROR"

export const SEND_COMMAND_REQUEST = "SEND_COMMAND_REQUEST"
export const SEND_COMMAND_SUCCESS = "SEND_COMMAND_SUCCESS"
export const SEND_COMMAND_ERROR = "SEND_COMMAND_ERROR"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR"

export const GET_INVITES_REQUEST = "GET_INVITES_REQUEST"
export const GET_INVITES_SUCCESS = "GET_INVITES_SUCCESS"
export const GET_INVITES_ERROR = "GET_INVITES_ERROR"

export const NEW_INVITE_REQUEST = "NEW_INVITE_REQUEST"
export const NEW_INVITE_SUCCESS = "NEW_INVITE_SUCCESS"
export const NEW_INVITE_ERROR = "NEW_INVITE_ERROR"

export const LOGOUT = "LOGOUT"
