/* Graph Explorer */

export const CONNECT_USERS_REQUEST = "CONNECT_USERS_REQUEST"
export const CONNECT_USERS_SUCCESS = "CONNECT_USERS_SUCCESS"
export const CONNECT_USERS_ERROR = "CONNECT_USERS_ERROR"
